export interface UniversityData {
  id: string;
  name: string;
  country: string;
  city: string;
  website: string;
  logo: string;
  ranking: number;
  description: string;
  programs: string[];
  tuitionInfo: string;
  admissionInfo: string;
  internationalInfo: string;
  scholarshipCount: number;
  establishedYear: number;
  studentCount: number;
  internationalStudentPercent: number;
}

export const seedUniversities: UniversityData[] = [
  {
    id: "harvard",
    name: "Harvard University",
    country: "United States",
    city: "Cambridge, MA",
    website: "https://www.harvard.edu",
    logo: "🎓",
    ranking: 1,
    description: "Oldest institution of higher learning in the United States, renowned for excellence across all disciplines with world-leading research output.",
    programs: ["Law", "Business", "Medicine", "Engineering", "Computer Science", "Public Health", "Education"],
    tuitionInfo: "$54,000 - $57,000 per year (full need-based financial aid available)",
    admissionInfo: "Highly selective (3-4% acceptance rate). Holistic review considering academics, extracurriculars, essays, and recommendations.",
    internationalInfo: "15-20% international students from 150+ countries. Need-blind admissions for international students.",
    scholarshipCount: 8,
    establishedYear: 1636,
    studentCount: 23000,
    internationalStudentPercent: 18
  },
  {
    id: "mit",
    name: "Massachusetts Institute of Technology",
    country: "United States",
    city: "Cambridge, MA",
    website: "https://www.mit.edu",
    logo: "🔬",
    ranking: 2,
    description: "World leader in science, engineering, and technology research with cutting-edge innovation across computing, AI, and physical sciences.",
    programs: ["Computer Science", "Engineering", "Physics", "Mathematics", "Economics", "Biology", "Management"],
    tuitionInfo: "$60,000 per year (need-based aid covering 100% of demonstrated need)",
    admissionInfo: "Extremely selective (4% acceptance). Focus on scientific aptitude, creativity, and problem-solving ability.",
    internationalInfo: "International students comprise 10% of undergraduate and 40% of graduate enrollment.",
    scholarshipCount: 6,
    establishedYear: 1861,
    studentCount: 11500,
    internationalStudentPercent: 30
  },
  {
    id: "oxford",
    name: "University of Oxford",
    country: "United Kingdom",
    city: "Oxford",
    website: "https://www.ox.ac.uk",
    logo: "🏛️",
    ranking: 3,
    description: "Oldest university in the English-speaking world, with tutorial-based teaching and world-class research across humanities and sciences.",
    programs: ["PPE", "Law", "Medicine", "Engineering", "Computer Science", "History", "English Literature"],
    tuitionInfo: "£9,250 (UK), £28,000 - £44,000 (International) depending on course",
    admissionInfo: "Rigorous academic requirements. Interviews and written tests required for most courses.",
    internationalInfo: "45% international students. Rhodes, Clarendon, and college-specific scholarships available.",
    scholarshipCount: 12,
    establishedYear: 1096,
    studentCount: 24500,
    internationalStudentPercent: 45
  },
  {
    id: "cambridge",
    name: "University of Cambridge",
    country: "United Kingdom",
    city: "Cambridge",
    website: "https://www.cam.ac.uk",
    logo: "📖",
    ranking: 4,
    description: "Collegiate university with exceptional natural sciences, mathematics, and engineering programs and Nobel-winning research tradition.",
    programs: ["Natural Sciences", "Engineering", "Mathematics", "Computer Science", "Medicine", "Economics", "Law"],
    tuitionInfo: "£9,250 (UK), £24,000 - £63,000 (International) depending on subject",
    admissionInfo: "Highly competitive. Subject-specific admissions assessments and college interviews required.",
    internationalInfo: "Gates Cambridge Scholarship is one of the world's most prestigious international graduate awards.",
    scholarshipCount: 10,
    establishedYear: 1209,
    studentCount: 24000,
    internationalStudentPercent: 42
  },
  {
    id: "stanford",
    name: "Stanford University",
    country: "United States",
    city: "Stanford, CA",
    website: "https://www.stanford.edu",
    logo: "🌲",
    ranking: 5,
    description: "Silicon Valley powerhouse excelling in entrepreneurship, computer science, engineering, and interdisciplinary innovation.",
    programs: ["Computer Science", "Engineering", "Business", "Medicine", "Law", "Education", "Earth Sciences"],
    tuitionInfo: "$62,000 per year (need-based financial aid, free tuition for families earning <$150,000)",
    admissionInfo: "Ultra-selective (3.7% acceptance). Values intellectual vitality, leadership, and impact.",
    internationalInfo: "10% international undergraduates, 35% international graduates. Knight-Hennessy Scholars program.",
    scholarshipCount: 7,
    establishedYear: 1885,
    studentCount: 17000,
    internationalStudentPercent: 23
  },
  {
    id: "tum",
    name: "Technical University of Munich",
    country: "Germany",
    city: "Munich",
    website: "https://www.tum.de",
    logo: "⚙️",
    ranking: 50,
    description: "Germany's top technical university specializing in engineering, natural sciences, and technology with strong industry partnerships.",
    programs: ["Mechanical Engineering", "Electrical Engineering", "Computer Science", "Physics", "Chemistry", "Mathematics"],
    tuitionInfo: "€0 tuition (public university), €144 semester contribution",
    admissionInfo: "Competitive selection based on academic records. German or English language proficiency required.",
    internationalInfo: "40% international students. Many English-taught master's programs. DAAD scholarships available.",
    scholarshipCount: 5,
    establishedYear: 1868,
    studentCount: 45000,
    internationalStudentPercent: 40
  },
  {
    id: "toronto",
    name: "University of Toronto",
    country: "Canada",
    city: "Toronto, ON",
    website: "https://www.utoronto.ca",
    logo: "🍁",
    ranking: 18,
    description: "Canada's top university and leading global research institution with strengths across all disciplines.",
    programs: ["Computer Science", "Engineering", "Medicine", "Business", "Law", "Public Health", "Arts & Sciences"],
    tuitionInfo: "CAD 6,000 (domestic), CAD 55,000 - 65,000 (international)",
    admissionInfo: "Competitive admissions. Strong academic performance and supplementary applications for many programs.",
    internationalInfo: "25% international students from 160+ countries. Lester B. Pearson and university entrance scholarships.",
    scholarshipCount: 9,
    establishedYear: 1827,
    studentCount: 95000,
    internationalStudentPercent: 25
  },
  {
    id: "anu",
    name: "Australian National University",
    country: "Australia",
    city: "Canberra",
    website: "https://www.anu.edu.au",
    logo: "🦘",
    ranking: 34,
    description: "Australia's national university with exceptional research focus, particularly strong in political science, Asia-Pacific studies, and physical sciences.",
    programs: ["Political Science", "International Relations", "Physics", "Astronomy", "Computer Science", "Economics"],
    tuitionInfo: "AUD 45,000 - 50,000 per year (international students)",
    admissionInfo: "Competitive entry. ATAR 90+ typically required for domestic students.",
    internationalInfo: "45% international students. ANU Chancellor's International Scholarship covers 25-50% tuition.",
    scholarshipCount: 6,
    establishedYear: 1946,
    studentCount: 25500,
    internationalStudentPercent: 45
  },
  {
    id: "tokyo",
    name: "University of Tokyo",
    country: "Japan",
    city: "Tokyo",
    website: "https://www.u-tokyo.ac.jp",
    logo: "🗾",
    ranking: 23,
    description: "Japan's most prestigious university, leading in science, engineering, and social sciences with deep industry connections.",
    programs: ["Engineering", "Natural Sciences", "Medicine", "Economics", "Law", "Information Science"],
    tuitionInfo: "¥535,800 per year (~$3,600) for all students including internationals",
    admissionInfo: "Rigorous entrance exams. International students may apply through special selection processes.",
    internationalInfo: "12% international students. MEXT scholarships available. Many English-taught graduate programs.",
    scholarshipCount: 4,
    establishedYear: 1877,
    studentCount: 28000,
    internationalStudentPercent: 12
  },
  {
    id: "eth",
    name: "ETH Zurich",
    country: "Switzerland",
    city: "Zurich",
    website: "https://ethz.ch",
    logo: "🏔️",
    ranking: 7,
    description: "Swiss Federal Institute of Technology, world-leading in engineering, natural sciences, mathematics, and architecture. Einstein's alma mater.",
    programs: ["Computer Science", "Mechanical Engineering", "Physics", "Mathematics", "Architecture", "Materials Science"],
    tuitionInfo: "CHF 1,460 per year for all students (approx. $1,600)",
    admissionInfo: "Competitive. Bachelor's in German, Master's programs in English. Strong academic record required.",
    internationalInfo: "40% international students. Excellence Scholarship & Opportunity Programme (ESOP) for exceptional master's students.",
    scholarshipCount: 3,
    establishedYear: 1855,
    studentCount: 24500,
    internationalStudentPercent: 40
  },
  {
    id: "nus",
    name: "National University of Singapore",
    country: "Singapore",
    city: "Singapore",
    website: "https://www.nus.edu.sg",
    logo: "🇸🇬",
    ranking: 11,
    description: "Asia's leading global university with comprehensive programs and world-class research in science, engineering, business, and computing.",
    programs: ["Computer Science", "Engineering", "Business", "Law", "Medicine", "Data Science", "Public Policy"],
    tuitionInfo: "SGD 17,000 - 30,000 (subsidized for locals), SGD 30,000 - 60,000 (international)",
    admissionInfo: "Highly selective. Strong A-levels, IB, or equivalent required.",
    internationalInfo: "30% international students. NUS Global Merit Scholarship, ASEAN scholarships available.",
    scholarshipCount: 7,
    establishedYear: 1905,
    studentCount: 40000,
    internationalStudentPercent: 30
  },
  {
    id: "kaist",
    name: "KAIST",
    country: "South Korea",
    city: "Daejeon",
    website: "https://www.kaist.ac.kr",
    logo: "🇰🇷",
    ranking: 42,
    description: "Korea Advanced Institute of Science and Technology, premier research university focused on science, technology, and innovation.",
    programs: ["Electrical Engineering", "Computer Science", "Mechanical Engineering", "Bio & Brain Engineering", "Industrial Design"],
    tuitionInfo: "Approx. $4,000 per semester. Most graduate students receive full funding.",
    admissionInfo: "Competitive. TOEFL/IELTS required. Strong STEM background essential.",
    internationalInfo: "15% international students. All PhD students receive full tuition waiver and stipend.",
    scholarshipCount: 5,
    establishedYear: 1971,
    studentCount: 11000,
    internationalStudentPercent: 15
  },
  {
    id: "delft",
    name: "Delft University of Technology",
    country: "Netherlands",
    city: "Delft",
    website: "https://www.tudelft.nl",
    logo: "🇳🇱",
    ranking: 57,
    description: "Leading European technical university specializing in engineering, design, and applied sciences with innovation focus.",
    programs: ["Civil Engineering", "Aerospace Engineering", "Architecture", "Computer Science", "Industrial Design"],
    tuitionInfo: "€2,314 (EEA), €18,750 - €22,000 (non-EEA) per year",
    admissionInfo: "Selective admissions. English proficiency and relevant bachelor's degree required for master's programs.",
    internationalInfo: "35% international students from 100+ countries. Justus & Louise van Effen Excellence Scholarships available.",
    scholarshipCount: 4,
    establishedYear: 1842,
    studentCount: 26500,
    internationalStudentPercent: 35
  },
  {
    id: "epfl",
    name: "École Polytechnique Fédérale de Lausanne",
    country: "Switzerland",
    city: "Lausanne",
    website: "https://www.epfl.ch",
    logo: "🔬",
    ranking: 16,
    description: "French-speaking Swiss Federal Institute of Technology, excelling in engineering, computer science, and life sciences.",
    programs: ["Computer Science", "Electrical Engineering", "Life Sciences", "Physics", "Architecture", "Materials Science"],
    tuitionInfo: "CHF 1,266 per year for all students (approx. $1,400)",
    admissionInfo: "Competitive. Bachelor's taught in French, master's and PhD primarily in English.",
    internationalInfo: "60% international students at master's/PhD level. Excellence fellowships for exceptional master's applicants.",
    scholarshipCount: 3,
    establishedYear: 1969,
    studentCount: 12500,
    internationalStudentPercent: 60
  },
  {
    id: "peking",
    name: "Peking University",
    country: "China",
    city: "Beijing",
    website: "https://www.pku.edu.cn",
    logo: "🇨🇳",
    ranking: 17,
    description: "China's oldest modern university, comprehensive research institution with strengths in humanities, sciences, and social sciences.",
    programs: ["Economics", "Computer Science", "Mathematics", "Physics", "International Relations", "Chinese Literature"],
    tuitionInfo: "CNY 26,000 - 50,000 per year (approx. $3,700 - $7,000)",
    admissionInfo: "Highly competitive. Entrance exam (Gaokao) for domestic, special application for international students.",
    internationalInfo: "20% international students. Chinese Government Scholarship, Yenching Scholarship available.",
    scholarshipCount: 6,
    establishedYear: 1898,
    studentCount: 47000,
    internationalStudentPercent: 20
  },
  {
    id: "imperial",
    name: "Imperial College London",
    country: "United Kingdom",
    city: "London",
    website: "https://www.imperial.ac.uk",
    logo: "👑",
    ranking: 6,
    description: "Science, engineering, medicine, and business specialist institution with intensive research focus and entrepreneurial culture.",
    programs: ["Engineering", "Computing", "Medicine", "Natural Sciences", "Business School"],
    tuitionInfo: "£9,250 (UK), £35,100 - £40,940 (International) depending on program",
    admissionInfo: "Highly selective. Strong emphasis on STEM subjects, interviews for Medicine.",
    internationalInfo: "60% international students. President's Scholarships and departmental funding available.",
    scholarshipCount: 8,
    establishedYear: 1907,
    studentCount: 20000,
    internationalStudentPercent: 60
  },
  {
    id: "sorbonne",
    name: "Sorbonne University",
    country: "France",
    city: "Paris",
    website: "https://www.sorbonne-universite.fr",
    logo: "🇫🇷",
    ranking: 60,
    description: "Historic Parisian university formed from the merger of Paris-Sorbonne and UPMC, renowned for humanities, sciences, and medicine.",
    programs: ["Literature", "Languages", "History", "Physics", "Chemistry", "Medicine", "Engineering"],
    tuitionInfo: "€170 - €601 per year (EEA), €2,770 - €3,770 (non-EEA)",
    admissionInfo: "Open admissions for EU citizens with baccalauréat. Competitive for international students.",
    internationalInfo: "20% international students. Eiffel Excellence Scholarship program for master's and PhD.",
    scholarshipCount: 4,
    establishedYear: 1257,
    studentCount: 55000,
    internationalStudentPercent: 20
  },
  {
    id: "lund",
    name: "Lund University",
    country: "Sweden",
    city: "Lund",
    website: "https://www.lunduniversity.lu.se",
    logo: "🇸🇪",
    ranking: 87,
    description: "One of northern Europe's oldest and most prestigious universities, offering 100+ English-taught master's programs.",
    programs: ["Engineering", "Natural Sciences", "Social Sciences", "Humanities", "Medicine", "Business"],
    tuitionInfo: "Free (EEA/Swiss), SEK 90,000 - 310,000 per year (non-EEA, approx. $8,500 - $29,000)",
    admissionInfo: "Competitive for international students. Bachelor's degree and English proficiency required.",
    internationalInfo: "20% international students. Lund University Global Scholarship covers 25-100% tuition.",
    scholarshipCount: 5,
    establishedYear: 1666,
    studentCount: 44000,
    internationalStudentPercent: 20
  },
  {
    id: "melbourne",
    name: "University of Melbourne",
    country: "Australia",
    city: "Melbourne",
    website: "https://www.unimelb.edu.au",
    logo: "🇦🇺",
    ranking: 14,
    description: "Australia's leading university with broad disciplinary strengths and graduate-entry professional degrees (Melbourne Model).",
    programs: ["Medicine", "Law", "Business", "Engineering", "Arts", "Science", "Education"],
    tuitionInfo: "AUD 32,000 - 50,000 per year (international)",
    admissionInfo: "Competitive. ATAR 90+ for most courses. Graduate entry for Medicine, Law, Teaching.",
    internationalInfo: "40% international students from 130 countries. Melbourne Graduate Scholarships and Chancellor's Scholarships.",
    scholarshipCount: 10,
    establishedYear: 1853,
    studentCount: 52000,
    internationalStudentPercent: 40
  },
  {
    id: "metu",
    name: "Middle East Technical University",
    country: "Turkey",
    city: "Ankara",
    website: "https://www.metu.edu.tr",
    logo: "🇹🇷",
    ranking: 300,
    description: "Turkey's premier technical university with English instruction, strong engineering and natural sciences programs.",
    programs: ["Computer Engineering", "Electrical Engineering", "Mechanical Engineering", "Physics", "Economics"],
    tuitionInfo: "Minimal fees for Turkish citizens, approx. $1,000 per year for international students",
    admissionInfo: "Competitive entrance exam for domestic students. International student quota with direct application.",
    internationalInfo: "10% international students mainly from Middle East, Central Asia, and Africa.",
    scholarshipCount: 3,
    establishedYear: 1956,
    studentCount: 32000,
    internationalStudentPercent: 10
  }
];
